image: docker:latest

variables:
  REPOSITORY_URL: docker pull saefulmuminin123/test-api-todos:1.0
  IMAGE_TAG: "1.0"

services:
  - docker:dind

before_script:
  - docker login

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building image..."
    - docker build
      -t saefulmuminin123/test-api-todos:1.0
      --build-arg PORT=$PORT
      --no-cache .
    - echo "Tagging image..."
    - docker tag saefulmuminin123/test-api-todos:1.0 $REPOSITORY_URL:$IMAGE_TAG
    - echo "Pushing image..."
    - docker push $REPOSITORY_URL:$IMAGE_TAG
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker stop  api-todos || true && docker rm  api-todos || true
    - docker container run -dt -p $PORT:$PORT --name  api-todos $REPOSITORY_URL:$IMAGE_TAG
    - docker image prune -f
  only:
    - main
